# Generated by Django 5.1.3 on 2025-10-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
