# Generated by Django 5.1.3 on 2025-10-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0002_shipment_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="purchase_order",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="waybill_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
