# Generated by Django 5.1.3 on 2026-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0003_alter_shipment_purchase_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="shipment_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
