# Generated by Django 5.1.3 on 2026-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0004_shipment_shipment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="mode_of_transport",
            field=models.CharField(
                choices=[
                    ("Sea Freight", "Sea Freight"),
                    ("Air Freight", "Air Freight"),
                    ("Courier", "Courier"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
