# Generated by Django 5.0.6 on 2024-12-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(blank=True, choices=[('freight', 'Freight'), ('valve_maintenance', 'Valve Maintenance'), ('valve_procurement', 'Valve Procurement'), ('pipeline', 'Pipeline'), ('blasting', 'Blasting'), ('training', 'Training'), ('other', 'Other')], max_length=20, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
